services:
  cinesync:
    image: sureshfizzy/cinesync:latest
    container_name: cinesync
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8082:8082"
      - "5173:5173"
    volumes:
      - /home:/home  # Mount home directory to provide access to home files
      - /mnt:/mnt  # Mount /mnt for access to external storage
      - ./db:/app/db  # Mount local db folder to persist database files
